- name: variables
  hosts: localhost
  vars:
    course: "devops"
    trainer: "vara"
    duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
    msg: "we are lerning {{course}} from trainer {{trainer}} duration is {{duration}}}"