- name: data types
  hosts: localhost
  vars:
    Course: Devops with AWS # this is string
    Tools: # start with "-" that is 'list'
    - linux
    - ansible 
    - shell
    Experience: #this is 'map' or dictonary
      DevOps: 3
      AWS: 2
      Docker: 4
    RealProject: true # boolin like 'true or false'
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"